[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid.workspace = true
thiserror.workspace = true
serde.workspace = true
chrono.workspace = true
sha2.workspace = true
hex.workspace = true
serde_json.workspace = true
